language: rust
sudo: required
os:
  - linux
  - osx
rust:
  - nightly
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo
before_install: ./.travis/before_install_$TRAVIS_OS_NAME.sh
script:
  - cargo test
after_success: |
  if [[ $TRAVIS_OS_NAME =~ linux ]]; then
    ./.travis/after_success.sh
  fi
